export const PHONE_TYPES = Object.freeze({
    IPHONE_X: 'IPHONE_X',
    IPHONE_8: 'IPHONE_8',
    IPHONE_7_PLUS_JET_BLACK: 'IPHONE_7_PLUS_JET_BLACK',
    IPHONE_XS_PLUS_GOLD: 'IPHONE_XS_PLUS_GOLD',
    IPHONE_XR_BLUE: 'IPHONE_XR_BLUE',
});
